export const lifters = [
  {
    id: "1",
    image: "/images/lifters/image1.webp",
    name: "Skid Steers",
  },
  {
    id: "2",
    image: "/images/lifters/image2.webp",
    name: "Mini Excavators",
  },
  {
    id: "3",
    image: "/images/lifters/image3.webp",
    name: "Excavators",
  },
  {
    id: "4",
    image: "/images/lifters/image4.webp",
    name: "Forklifts",
  },
  {
    id: "5",
    image: "/images/lifters/image5.webp",
    name: "Lifts",
  },
  {
    id: "6",
    image: "/images/lifters/image6.webp",
    name: "Dozers",
  },
  {
    id: "7",
    image: "/images/lifters/image7.webp",
    name: "Trenchers / Cable Plows",
  },
  {
    id: "8",
    image: "/images/lifters/image8.webp",
    name: "Cranes",
  },
  {
    id: "9",
    image: "/images/lifters/image9.webp",
    name: "Loader Backhoes",
  },
  {
    id: "10",
    image: "/images/lifters/image10.webp",
    name: "Wheel Loaders",
  },
  {
    id: "11",
    image: "/images/lifters/image11.webp",
    name: "Forestry Equipment",
  },
  {
    id: "12",
    image: "/images/lifters/image12.webp",
    name: "Drills",
  },
  {
    id: "13",
    image: "/images/lifters/image13.webp",
    name: "Motor Graders",
  },
  {
    id: "14",
    image: "/images/lifters/image14.webp",
    name: "Sweepers / Broom Equipment",
  },
  {
    id: "15",
    image: "/images/lifters/image15.webp",
    name: "Aggregate Equipment",
  },
  {
    id: "16",
    image: "/images/lifters/image16.webp",
    name: "Telehandlers",
  },
  {
    id: "17",
    image: "/images/lifters/image17.webp",
    name: "Off-Highway Trucks",
  },
  {
    id: "18",
    image: "/images/lifters/image18.webp",
    name: "Asphalt / Pavers / Concrete Equipment",
  },
  {
    id: "19",
    image: "/images/lifters/image19.webp",
    name: "Construction Attachments",
  },
  {
    id: "20",
    image: "/images/lifters/image20.webp",
    name: "Dismantled Machines",
  },
  {
    id: "21",
    image: "/images/lifters/image21.webp",
    name: "Parts",
  },
];

export const blogsData = [
  {
    slug: "best-practices-of-hr-management",
    image: "/images/blog1.jpg",
    category: "NEWS",
    date: "28/08/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "Best Practices Of HR Management",
  },
  {
    slug: "10-tips-to-find-best-backhoe",
    image: "/images/blog2.jpg",
    category: "UPDATES",
    date: "28/03/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "10-tips-to-find-best-backhoe",
  },
  {
    slug: "how-to-setup-a-construction-site",
    image: "/images/blog3.jpg",
    category: "NEWS",
    date: "28/08/2017",
    author: "root",
    comments: "NO COMMENTS",
    title: "how-to-setup-a-construction-site",
  },
  {
    slug: "best-practices-of-hr-management",
    image: "/images/blog1.jpg",
    category: "NEWS",
    date: "28/08/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "Best Practices Of HR Management",
  },
  {
    slug: "10-tips-to-find-best-backhoe",
    image: "/images/blog2.jpg",
    category: "UPDATES",
    date: "28/03/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "10-tips-to-find-best-backhoe",
  },
  {
    slug: "how-to-setup-a-construction-site",
    image: "/images/blog3.jpg",
    category: "NEWS",
    date: "28/08/2017",
    author: "root",
    comments: "NO COMMENTS",
    title: "how-to-setup-a-construction-site",
  },
  {
    slug: "best-practices-of-hr-management",
    image: "/images/blog1.jpg",
    category: "NEWS",
    date: "28/08/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "Best Practices Of HR Management",
  },
  {
    slug: "10-tips-to-find-best-backhoe",
    image: "/images/blog2.jpg",
    category: "UPDATES",
    date: "28/03/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "10-tips-to-find-best-backhoe",
  },
  {
    slug: "how-to-setup-a-construction-site",
    image: "/images/blog3.jpg",
    category: "NEWS",
    date: "28/08/2017",
    author: "root",
    comments: "NO COMMENTS",
    title: "how-to-setup-a-construction-site",
  },
  {
    slug: "best-practices-of-hr-management",
    image: "/images/blog1.jpg",
    category: "NEWS",
    date: "28/08/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "Best Practices Of HR Management",
  },
  {
    slug: "10-tips-to-find-best-backhoe",
    image: "/images/blog2.jpg",
    category: "UPDATES",
    date: "28/03/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "10-tips-to-find-best-backhoe",
  },
  {
    slug: "how-to-setup-a-construction-site",
    image: "/images/blog3.jpg",
    category: "NEWS",
    date: "28/08/2017",
    author: "root",
    comments: "NO COMMENTS",
    title: "how-to-setup-a-construction-site",
  },
  {
    slug: "best-practices-of-hr-management",
    image: "/images/blog1.jpg",
    category: "NEWS",
    date: "28/08/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "Best Practices Of HR Management",
  },
  {
    slug: "10-tips-to-find-best-backhoe",
    image: "/images/blog2.jpg",
    category: "UPDATES",
    date: "28/03/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "10-tips-to-find-best-backhoe",
  },
  {
    slug: "how-to-setup-a-construction-site",
    image: "/images/blog3.jpg",
    category: "NEWS",
    date: "28/08/2017",
    author: "root",
    comments: "NO COMMENTS",
    title: "how-to-setup-a-construction-site",
  },
  {
    slug: "best-practices-of-hr-management",
    image: "/images/blog1.jpg",
    category: "NEWS",
    date: "28/08/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "Best Practices Of HR Management",
  },
  {
    slug: "10-tips-to-find-best-backhoe",
    image: "/images/blog2.jpg",
    category: "UPDATES",
    date: "28/03/2019",
    author: "root",
    comments: "NO COMMENTS",
    title: "10-tips-to-find-best-backhoe",
  },
  {
    slug: "how-to-setup-a-construction-site",
    image: "/images/blog3.jpg",
    category: "NEWS",
    date: "28/08/2017",
    author: "root",
    comments: "NO COMMENTS",
    title: "how-to-setup-a-construction-site",
  },
];

export const slideData = [
  {
    image: "/svg/slider/caterpillar.svg",
    link: "#",
    btnTitle: "Caterpillar",
  },
  {
    image: "/svg/slider/deere.svg",
    link: "#",
    btnTitle: "Deere",
  },
  {
    image: "/svg/slider/genie.svg",
    link: "#",
    btnTitle: "Genie",
  },
  {
    image: "/svg/slider/jlg.svg",
    link: "#",
    btnTitle: "JLG",
  },
  {
    image: "/svg/slider/komatsu.svg",
    link: "#",
    btnTitle: "Komatsu",
  },
  // {
  //   image: "/svg/slider/volvo.svg",
  //   link: "#",
  //   btnTitle: "Volvo",
  // },
  {
    image: "/svg/slider/bobcat.svg",
    link: "#",
    btnTitle: "Bobcat",
  },
  {
    image: "/svg/slider/case.svg",
    link: "#",
    btnTitle: "Case",
  },
  {
    image: "/svg/slider/jcb.svg",
    link: "#",
    btnTitle: "JCB",
  },
  {
    image: "/svg/slider/hyundai.svg",
    link: "#",
    btnTitle: "Hyundai",
  },
  {
    image: "/svg/slider/new-holland.svg",
    link: "#",
    btnTitle: "New Holland",
  },
  {
    image: "/svg/slider/doosan.svg",
    link: "#",
    btnTitle: "Doosan",
  },
];

export const categoryList = [
  "Disks",
  "Tractors - 300 HP or Greater",
  "Tractors - 175 HP or 299",
];

export const filterCategories = [
  {
    categoryName: "Construction Equipment",
    subcategories: [
      "Aerial Platform Lift Trucks",
      "Air Compressors",
      "Boring Machines",
      "Compactors",
      "Crawler Carriers",
      "Crawler Loaders",
      "Dumpers",
      "Fleet Management",
      "Generators",
      "Heaters",
      "Light Towers",
      "Miscellaneous Equipment",
      "Oilfield Equipment",
      "Pipelayers",
      "Pumps",
      "Scrap Processing / Demolition Equipment",
      "Scrapers",
      "Skip Loaders",
      "Straw Blowers / Hydroseeders",
      "Water Equipment",
      "Other Items",
    ],
  },
  {
    categoryName: "Trucks & Trailers",
    subcategories: [
      "Attenuator Trucks",
      "Boom Trucks",
      "Bucket Trucks",
      "Crane Trucks",
      "Digger Derrick Trucks",
      "Dump",
      "Dump - Transfer Trucks",
      "Dump Trucks",
      "Flatbed-Dump Trucks",
      "Fuel Trucks / Lube Trucks",
      "Grapple Trucks",
      "Mixer Trucks / Asphalt Trucks / Concrete Trucks",
      "Service Trucks / Utility Trucks / Mechanic Trucks",
      "Sweeper Trucks",
      "Vacuum / Industrial",
      "Water",
      "Trailers",
      "Dump",
      "Drop Deck",
      "Flat",
      "Lowboy",
      "Tag",
      "Tank",
    ],
  },
  {
    categoryName: "RVs",
    subcategories: [
      "Recreational Vehicles (Motorhomes, Fifth Wheels, Travel Trailers, etc.)",
    ],
  },
  {
    categoryName: "Farm Equipment",
    subcategories: [
      "Disks",
      "Tractors - 300 HP or Greater",
      "Tractors - 175 HP to 299 HP",
    ],
  },
];

export const sortOptions = [
  { name: "Most Popular", href: "#", current: true },
  { name: "Best Rating", href: "#", current: false },
  { name: "Newest", href: "#", current: false },
  { name: "Price: Low to High", href: "#", current: false },
  { name: "Price: High to Low", href: "#", current: false },
];
export const subCategories = [
  { name: "Boom Lift", href: "#" },
  { name: "Carry Deck Crane", href: "#" },
  { name: "Compaction Equipment", href: "#" },
  { name: "Forklift", href: "#" },
  { name: "Uncategorized", href: "#" },
];
export const filters = [
  {
    id: "city",
    name: "Filter by City",
    options: [
      { value: "new-arrivals", label: "Los Angeles, CA", checked: false },
      { value: "sale", label: "Texas, TX ", checked: false },
      { value: "travel", label: "Miami, CA ", checked: true },
      { value: "organization", label: "California, CA ", checked: false },
      { value: "accessories", label: "New York, NY ", checked: false },
    ],
  },
  {
    id: "price",
    name: "Filter by Price",
    // options: [
    //   { value: "2l", label: "2L", checked: false },
    //   { value: "6l", label: "6L", checked: false },
    //   { value: "12l", label: "12L", checked: false },
    //   { value: "18l", label: "18L", checked: false },
    //   { value: "20l", label: "20L", checked: false },
    //   { value: "40l", label: "40L", checked: true },
    // ],
  },
];
export const products = [
  {
    id: "1",
    name: "120ft – 150ft-Articulating Boom Lift",
    href: "1",
    price: "$50",
    imageSrc: "/images/product700.webp",
    imageAlt:
      "White fabric pouch with white zipper, black zipper pull, and black elastic loop.",
  },
  {
    id: "2",
    name: "30 ft, Narrow, Electric, Articulating Boom Lift",
    href: "2",
    price: "$140",
    imageSrc: "/images/product700.webp",
    imageAlt:
      "Front of tote bag with washed black canvas body, black straps, and tan leather handles and accents.",
  },
  {
    id: "3",
    name: "30ft – 40ft-Articulating Boom Lift",
    href: "3",
    price: "$140",
    imageSrc: "/images/product700.webp",
    imageAlt:
      "Front of tote bag with washed black canvas body, black straps, and tan leather handles and accents.",
  },
  // More products...
];
